### PR TITLE
Allow to add version metadata check rules before triggering a release

### PR DESCRIPTION
**Pull request by sengineer0**
Ref: https://github.com/biothings/biothings.api/issues/284

### CODE REVIEW

**Comment by newgene** [comment]
@sengineer0 the implementation looks good to me. Just one question, if A hub instance needs to override this method with its own validation rules in a `AutoHubFeature` subclass, is there an easy way to specify to use this new subclass?

**Comment by sengineer0** [comment]
> @sengineer0 the implementation looks good to me. Just one question, if A hub instance needs to override this method with its own validation rules in a `AutoHubFeature` subclass, is there an easy way to specify to use this new subclass?

@newgene as I see, currently we doesn't support an easy way to specify subclass of `AutoHubFeature`, when hub configures autohub feature, it always import and instantiate  the `biothings.hub.standalone.AutoHubFeature`

I suggest that, we can add a config, to allow specify what class to use as autohub manager, default can be the `biothings.hub.standalone.AutoHubFeature`

What do you think ?

**Comment by newgene** [comment]
@sengineer0 every hub instance will have this [bin/hub.py](https://github.com/biothings/mychem.info/blob/master/src/bin/hub.py), where we typically customize a hub. If you can see an easy way to use a `AutoHubFeature` subclass there, we should be good. A customization example in that hub.py is the use of `MyChemDataBuilder` for that hub.

**Comment by newgene** [comment]
I will merge this PR first, but please update this PR comment (or code) if you have more info regarding how to use it.

**Pull request merged**
