### PR TITLE
Support more fieds in manifest file

### PR DESCRIPTION
**Pull request by remoteeng00**
- Ref: https://github.com/biothings/biothings.api/issues/254
- There are two commits here, one for fix typo and one for update code logic.
- We need update the web app for parsing and displaying those fields
- New manifest file looked likes:
```---
version: '0.3'
display_name: "Test test"
biothing_type: "biothing_type_test"
requires:
- pandas
- numpy
dumper:
  data_url:
  - https://s3.pgkb.org/data/annotations.zip
  - https://s3.pgkb.org/data/drugLabels.zip
  - https://s3.pgkb.org/data/occurrences.zip
  uncompress: true
uploaders:
- name: annotations
  parser: parser:load_annotations
  mapping: parser:custom_annotations_mapping
  ignore_duplicates: false
- name: druglabels
  parser: parser:load_druglabels
  ignore_duplicates: false
- name: occurrences
  parser: parser:load_occurrences
  ignore_duplicates: false
```
New fields will be fetched on the get source info API:
ex: GET /source/pharmgkb
response: 
```json
{
  "result": {
    "_id": "pharmgkb",
    "name": "pharmgkb",
    "download": {
      "status": "success"
      }
    },
    "upload": {
      "sources": {
      }
    },
    "mapping": {
    },
    "__metadata__": {
      "src_meta": {}
    },
    "inspect": {
    },
    "count": 6920,
    "data_plugin": {
      "plugin": {
        "url": "local://pharmgkb",
        "type": "local",
        "active": true,
        "loader": "manifest",
        "display_name": "Test test",
        "biothing_type": "biothing_type_test"
      },
      "download": {
      }
    }
  },
  "status": "ok"
}
```

### CODE REVIEW

**Comment by newgene** [comment]
this PR looks good to me. Pending to merge after we release v0.11.0. Will leave this feature to the next release.

**Comment by newgene** [comment]
@sengineer0 I created a corresponding biothings_studio issue to add the support in UI: https://github.com/biothings/biothings_studio/issues/106

**Comment by newgene** [comment]
@remoteeng00 I noticed that `biothings_type` should actually be `biothing_type` without `s`. Please change it accordingly (both the code and manifest example above. Also cc'ing @sengineer0 for any changes needed on `biothings_studio` side.

And since `biothings_type` could be a possible typo, you may allow it as an alias in manifest file, but logs a warning for the correct name.

**Comment by sengineer0** [comment]
> @remoteeng00 I noticed that `biothings_type` should actually be `biothing_type` without `s`. Please change it accordingly (both the code and manifest example above. Also cc'ing @sengineer0 for any changes needed on `biothings_studio` side.
> 
> And since `biothings_type` could be a possible typo, you may allow it as an alias in manifest file, but logs a warning for the correct name.

I will review my PR and update if needed.
@newgene

**Comment by sengineer0** [comment]
@newgene 
I updated my PR for Studio
@remoteeng00   Please resolve conflict and change the biothings_type to biothing_type in your PR. Thanks

**Comment by remoteeng00** [comment]
>@remoteeng00 Please resolve conflict and change the biothings_type to biothing_type in your PR. Thanks

It's updated.

**Comment by newgene** [comment]
@remoteeng00 we should update the manifest file template to add these two optional fields. That template file may not be merged in `master` yet, in this case, just make corresponding changes to the admin-cli branch and reference this PR and issue.

**Comment by remoteeng00** [comment]
Ok, sure, it will be update in the next commit!

**Pull request merged**
