### PR TITLE
refactor uitls.diff: split into 2 files, one not require to setup Biothings Hub, the other still requires

### PR DESCRIPTION
**Pull request by sengineer0**
The current biothings.utils.diff requires to setup biothings hub, before the user can import any helper functions in this module.
It is a time-consuming works, and quite hard for the dataplugin's developer to use module's functions for compare these datasource and the data stored in the mongo, or Elastic Search

This PR try to refactor `biothings.utils.diff` module, split it into 2 separate modules:
-  diff_common.py: contains only helper function which can be used without biothings hub
-  diff.py: contains the functions which requires hub's feature: config, working with the backend, ...

In order to compare 2 collection sets, the developer can use:
- `diff_common.diff_collection`: which receives 2 valid data structures
- `diff_common.diff_json_files`: which receives 2 paths of valid json files

Note:
- valid data structure is a list of dict, and each dict will contains at least a `_id` field to be used to compared
- the developer can export the data from mongo by using `mongoexport` command, with these flags: `--jsonArray --type=json`
- the developer can export the data from Elastic Search by call to the _search api, fetch all data

### CODE REVIEW

**Comment by newgene** [comment]
I believe this PR is needed for the "admin cli" feature, let's merge it into `add-biothings-admin-cli` branch first. @sengineer0 @remoteeng00

**Comment by sengineer0** [comment]
> I believe this PR is needed for the "admin cli" feature, let's merge it into `add-biothings-admin-cli` branch first. @sengineer0 @remoteeng00

@newgene  ok sure. I will rebase my PR and retest.

**Comment by sengineer0** [comment]
> I believe this PR is needed for the "admin cli" feature, let's merge it into `add-biothings-admin-cli` branch first. @sengineer0 @remoteeng00

@newgene It's updated.

**Comment by sengineer0** [comment]
@newgene It's updated.

**Comment by newgene** [comment]
@remoteeng00 can you merge and verify it's working with this cli branch?

**Comment by remoteeng00** [comment]
yes, sure!

**Pull request merged**
